package com.adyen.services.payment;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-03-27T17:10:25.154-05:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://payment.services.adyen.com", name = "PaymentPortType")
@XmlSeeAlso({com.adyen.services.common.ObjectFactory.class, ObjectFactory.class})
public interface PaymentPortType {

    @WebResult(name = "result", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "fundTransfer", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.FundTransfer")
    @WebMethod
    @ResponseWrapper(localName = "fundTransferResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.FundTransferResponse")
    public com.adyen.services.payment.FundTransferResult fundTransfer(
        @WebParam(name = "request", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.FundTransferRequest request
    ) throws ServiceException;

    @WebResult(name = "result", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "refundWithData", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.RefundWithData")
    @WebMethod
    @ResponseWrapper(localName = "refundWithDataResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.RefundWithDataResponse")
    public com.adyen.services.payment.PaymentResult refundWithData(
        @WebParam(name = "request", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.PaymentRequest request
    ) throws ServiceException;

    @WebResult(name = "captureResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "capture", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Capture")
    @WebMethod
    @ResponseWrapper(localName = "captureResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CaptureResponse")
    public com.adyen.services.payment.ModificationResult capture(
        @WebParam(name = "modificationRequest", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.ModificationRequest modificationRequest
    ) throws ServiceException;

    @WebResult(name = "refundResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "refund", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Refund")
    @WebMethod
    @ResponseWrapper(localName = "refundResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.RefundResponse")
    public com.adyen.services.payment.ModificationResult refund(
        @WebParam(name = "modificationRequest", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.ModificationRequest modificationRequest
    ) throws ServiceException;

    @WebResult(name = "authoriseReferralResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "authoriseReferral", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.AuthoriseReferral")
    @WebMethod
    @ResponseWrapper(localName = "authoriseReferralResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.AuthoriseReferralResponse")
    public com.adyen.services.payment.ModificationResult authoriseReferral(
        @WebParam(name = "modificationRequest", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.ModificationRequest modificationRequest
    ) throws ServiceException;

    @WebResult(name = "cancelResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "cancel", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Cancel")
    @WebMethod
    @ResponseWrapper(localName = "cancelResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CancelResponse")
    public com.adyen.services.payment.ModificationResult cancel(
        @WebParam(name = "modificationRequest", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.ModificationRequest modificationRequest
    ) throws ServiceException;

    @WebResult(name = "paymentResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "authorise3d", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Authorise3D")
    @WebMethod(operationName = "authorise3d")
    @ResponseWrapper(localName = "authorise3dResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Authorise3DResponse")
    public com.adyen.services.payment.PaymentResult authorise3D(
        @WebParam(name = "paymentRequest3d", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.PaymentRequest3D paymentRequest3D
    ) throws ServiceException;

    @WebResult(name = "response", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "balanceCheck", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.BalanceCheck")
    @WebMethod
    @ResponseWrapper(localName = "balanceCheckResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.BalanceCheckResponse")
    public com.adyen.services.payment.BalanceCheckResult balanceCheck(
        @WebParam(name = "request", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.BalanceCheckRequest request
    ) throws ServiceException;

    @WebResult(name = "response", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "directdebit", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Directdebit")
    @WebMethod
    @ResponseWrapper(localName = "directdebitResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.DirectdebitResponse")
    public com.adyen.services.payment.DirectDebitResponse2 directdebit(
        @WebParam(name = "request", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.DirectDebitRequest request
    ) throws ServiceException;

    @WebResult(name = "cancelOrRefundResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "cancelOrRefund", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CancelOrRefund")
    @WebMethod
    @ResponseWrapper(localName = "cancelOrRefundResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CancelOrRefundResponse")
    public com.adyen.services.payment.ModificationResult cancelOrRefund(
        @WebParam(name = "modificationRequest", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.ModificationRequest modificationRequest
    ) throws ServiceException;

    @WebResult(name = "paymentResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "authorise", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.Authorise")
    @WebMethod
    @ResponseWrapper(localName = "authoriseResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.AuthoriseResponse")
    public com.adyen.services.payment.PaymentResult authorise(
        @WebParam(name = "paymentRequest", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.PaymentRequest paymentRequest
    ) throws ServiceException;

    @WebResult(name = "paymentResult", targetNamespace = "http://payment.services.adyen.com")
    @RequestWrapper(localName = "checkFraud", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CheckFraud")
    @WebMethod
    @ResponseWrapper(localName = "checkFraudResponse", targetNamespace = "http://payment.services.adyen.com", className = "com.adyen.services.payment.CheckFraudResponse")
    public com.adyen.services.payment.PaymentResult checkFraud(
        @WebParam(name = "paymentRequest", targetNamespace = "http://payment.services.adyen.com")
        com.adyen.services.payment.PaymentRequest paymentRequest
    ) throws ServiceException;
}
