package com.adyen.services.recurring;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2013-03-27T17:10:22.322-05:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://recurring.services.adyen.com", name = "RecurringPortType")
@XmlSeeAlso({ObjectFactory.class, com.adyen.services.common.ObjectFactory.class, com.adyen.services.payment.ObjectFactory.class})
public interface RecurringPortType {

    @WebResult(name = "result", targetNamespace = "http://recurring.services.adyen.com")
    @RequestWrapper(localName = "listRecurringDetails", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.ListRecurringDetails")
    @WebMethod
    @ResponseWrapper(localName = "listRecurringDetailsResponse", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.ListRecurringDetailsResponse")
    public com.adyen.services.recurring.RecurringDetailsResult listRecurringDetails(
        @WebParam(name = "request", targetNamespace = "http://recurring.services.adyen.com")
        com.adyen.services.recurring.RecurringDetailsRequest request
    ) throws ServiceException;

    @WebResult(name = "recurringResult", targetNamespace = "http://recurring.services.adyen.com")
    @RequestWrapper(localName = "deactivateRecurring", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.DeactivateRecurring")
    @WebMethod
    @ResponseWrapper(localName = "deactivateRecurringResponse", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.DeactivateRecurringResponse")
    public com.adyen.services.recurring.RecurringResult deactivateRecurring(
        @WebParam(name = "recurringRequest", targetNamespace = "http://recurring.services.adyen.com")
        com.adyen.services.recurring.RecurringRequest recurringRequest
    ) throws ServiceException;

    @WebResult(name = "recurringResult", targetNamespace = "http://recurring.services.adyen.com")
    @RequestWrapper(localName = "submitRecurring", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.SubmitRecurring")
    @WebMethod
    @ResponseWrapper(localName = "submitRecurringResponse", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.SubmitRecurringResponse")
    public com.adyen.services.recurring.RecurringResult submitRecurring(
        @WebParam(name = "recurringRequest", targetNamespace = "http://recurring.services.adyen.com")
        com.adyen.services.recurring.RecurringRequest recurringRequest
    ) throws ServiceException;

    @WebResult(name = "result", targetNamespace = "http://recurring.services.adyen.com")
    @RequestWrapper(localName = "storeToken", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.StoreToken")
    @WebMethod
    @ResponseWrapper(localName = "storeTokenResponse", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.StoreTokenResponse")
    public com.adyen.services.recurring.StoreTokenResult storeToken(
        @WebParam(name = "request", targetNamespace = "http://recurring.services.adyen.com")
        com.adyen.services.recurring.StoreTokenRequest request
    ) throws ServiceException;

    @WebResult(name = "recurringResult", targetNamespace = "http://recurring.services.adyen.com")
    @RequestWrapper(localName = "initialiseRecurring", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.InitialiseRecurring")
    @WebMethod
    @ResponseWrapper(localName = "initialiseRecurringResponse", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.InitialiseRecurringResponse")
    public com.adyen.services.recurring.RecurringResult initialiseRecurring(
        @WebParam(name = "recurringRequest", targetNamespace = "http://recurring.services.adyen.com")
        com.adyen.services.recurring.RecurringRequest recurringRequest
    ) throws ServiceException;

    @WebResult(name = "result", targetNamespace = "http://recurring.services.adyen.com")
    @RequestWrapper(localName = "disable", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.Disable")
    @WebMethod
    @ResponseWrapper(localName = "disableResponse", targetNamespace = "http://recurring.services.adyen.com", className = "com.adyen.services.recurring.DisableResponse")
    public com.adyen.services.recurring.DisableResult disable(
        @WebParam(name = "request", targetNamespace = "http://recurring.services.adyen.com")
        com.adyen.services.recurring.DisableRequest request
    ) throws ServiceException;
}
